language: cpp
sudo: required

branches:
  only: 
    - master

#os:
#    - linux

#compiler:
#    - clang
#    - g++-6

## env:
##    - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug
##    - TARGET_CPU=x64 BUILD_CONFIGURATION=Release

matrix:
  include:
    # clang 5 C++11/14/1z Debug/Release-ASAN libc++, 11 Debug libstdc++
    - env: CLANG_VERSION=5.0 BUILD_TYPE=Debug CPP=11 ASAN=On LIBCXX=On CLANG_MODULES=Off BOOST=Off
      os: linux
      addons: &clang5
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise


    # gcc-6 C++11/14/1z Debug/Release
    - env: GCC_VERSION=6 BUILD_TYPE=Debug CPP=11 ASAN=On LIBCXX=Off BOOST=Off
      os: linux
      addons: &gcc6
        apt:
          packages:
            - g++-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test


install:
#    - cd $CHECKOUT_PATH
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make

#     sudo apt-get purge cmake
#     mkdir ~/temp
#     cd ~/temp
#     wget https://cmake.org/files/v3.9/cmake-3.9.1.tar.gz
#     tar -xzvf cmake-3.9.1.tar.gz
#     cd cmake-3.9.1/
#     ./bootstrap
#     make -j4
#     sudo make install

# install: 
#  - sudo apt-get install --allow-unauthenticated -qq clang++-4.0
#  - export CXX="clang++-4.0"

script:
    - ctest -VV

notifications:
    email: false