dependencies:
  pre:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
    - sudo apt-get update
    - sudo apt-get install util-linux clang-5.0 g++-6 valgrind
    
  override:
    - mkdir build; cd build; cmake ..; make
test:
  override:
    - cd build
    - ctest -VV
checkout:
  post:
    - git submodule init
    - git submodule update
