version: 2

workflows:
  version: 2
  default:
    jobs:
      - build-with-clang-and-test
          # filters:
          #   branches:
          #     only: master
          


# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master


step-library:
  - &install-cmake-3-9-1
      run:
        name: Install CMake 3.9.1
        command: |
          curl -sSL https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz | sudo tar -xzC /opt 
#          export PATH=/opt/cmake-3.9.1-Linux-x86_64/bin:$PATH
          echo '' >> ~/.bashrc
          echo 'export PATH=/opt/cmake-3.9.1-Linux-x86_64/bin:$PATH' >> ~/.bashrc
          echo $PATH
  
  - &install-compilers-and-dependencies
      run:
        name: Install compilers and dependencies
        command: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo add-apt-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
          sudo apt-get update
          sudo apt-get install util-linux clang-5.0 g++-6 valgrind 
          sudo apt-get install libboost-dev libboost-system-dev libboost-filesystem-dev

  - &init-git-submodules
      run:
        name: Init Git submodules
        command: |
          git submodule init
          git submodule update

  - &execute-cmake-and-make
      run:
        name: Execute CMake and Make
        command: |
          mkdir build
          cd build
          cmake ..
          make

  - &perform-unit-tests
      run:
        name: Perform Unit tests  
        command: |
          ctest -VV


jobs:
# ------------------------------------------------------------------------------
  build-with-clang-and-test:
    machine: true
    #working_directory: 
    environment:
      LIBSYSCONFCPUS: 4
      JOBS: 4
      BUILDTYPE: Debug
      CXX: clang++5
      CC: clang-5
    steps:
      - *install-cmake-3-9-1
      - *install-compilers-and-dependencies
      - checkout
      - *init-git-submodules
      - *execute-cmake-and-make
      - *perform-unit-tests
